[project]
name = "pesiton-rag-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Shamal De Silva", email = "shamalgithub@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.42.4",
    "botocore>=1.42.4",
    "fastapi>=0.123.10",
    "instructor[bedrock]>=1.13.0",
    "motor>=3.7.1",
    "pydantic>=2.12.5",
    "python-dotenv>=1.2.1",
    "python-multipart>=0.0.20",
    "uvicorn>=0.38.0",
]

[build-system]
requires = ["uv_build>=0.9.9,<0.10.0"]
build-backend = "uv_build"
